# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Core string extraction for locale coverage (no catalogs needed).

Collects every user-visible English string declared by the CORE
(`main.py` + `lynceus/**`: `t()` literals, node display strings, builtin
port names) into a deterministic set. The extensions repository tests its
locale packs against a snapshot of this set
(`locales/_core_strings.json`, regenerated by the snapshot tool on each
release) — so this module must never touch `extensions/` or catalogs.

`extract_core_strings()` is reused by `test_locale_coverage.py` and by the
snapshot tool.
"""

import ast
import json
import pkgutil
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Core checkout (sources next to tests) vs extensions repo (core is a
#: dependency: only the snapshot + own nodes are visible).
IS_CORE_CHECKOUT = (ROOT / "lynceus").is_dir()

SNAPSHOT_VERSION = 1


def _is_number(text: str) -> bool:
    try:
        float(text)
        return True
    except ValueError:
        return False


def _static_t_literals() -> set[str]:
    """Every t('<literal>') in main.py + lynceus/** (AST, no execution)."""
    files = [ROOT / "main.py"]
    for path in sorted((ROOT / "lynceus").rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        files.append(path)
    found = set()
    for path in files:
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (OSError, SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            if not (isinstance(func, ast.Name) and func.id == "t"):
                continue
            if not node.args:
                continue
            arg = node.args[0]
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                found.add(arg.value)
    return found


def _str(node) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _dict_str(node) -> dict:
    out = {}
    if isinstance(node, ast.Dict):
        for key, value in zip(node.keys, node.values):
            name = _str(key)
            if name is not None:
                out[name] = value
    return out


def node_file_strings(path: Path) -> set[str]:
    """Display strings declared by one core node/variant .py (AST)."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, UnicodeDecodeError):
        return set()
    assigns = {}
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
        ):
            assigns[node.targets[0].id] = node.value
    out = set()
    for key in (
        "NODE_NAME",
        "NODE_CATEGORY",
        "NODE_SUBCATEGORY",
        "NODE_DESCRIPTION",
        "VARIANT_LABEL",
    ):
        value = _str(assigns.get(key)) if assigns.get(key) is not None else None
        if value:
            out.add(value)
    specs = assigns.get("PROCESSING_SPECS")
    if specs is not None:
        schema = _dict_str(specs).get("config_schema")
        if schema is not None:
            for param, pspec in _dict_str(schema).items():
                out.add(param.replace("_", " "))
                fields = _dict_str(pspec)
                for field in ("description", "impact", "group"):
                    value = _str(fields.get(field))
                    if value:
                        out.add(value)
                for options_key in ("options", "enum"):
                    options = fields.get(options_key)
                    if isinstance(options, ast.List):
                        for elt in options.elts:
                            if isinstance(elt, (ast.Tuple, ast.List)) and elt.elts:
                                value = _str(elt.elts[0])
                            else:
                                value = _str(elt)
                            if value and not _is_number(value):
                                out.add(value)
    for ports_key in ("INPUTS", "OUTPUTS"):
        ports = assigns.get(ports_key)
        if isinstance(ports, ast.Tuple):
            for elt in ports.elts:
                if isinstance(elt, ast.Call):
                    for keyword in elt.keywords:
                        if keyword.arg == "name":
                            value = _str(keyword.value)
                            if value:
                                out.add(value)
                elif isinstance(elt, ast.Tuple) and len(elt.elts) == 2:
                    value = _str(elt.elts[1])
                    if value:
                        out.add(value)
    return out


def _core_node_files() -> list[Path]:
    import lynceus.nodes as package

    files = []
    for module in pkgutil.walk_packages(
        package.__path__, prefix=f"{package.__name__}."
    ):
        if module.ispkg:
            continue
        try:
            import importlib.util

            spec = importlib.util.find_spec(module.name)
            origin = spec.origin if spec else None
        except (ImportError, AttributeError, ValueError):
            origin = None
        if origin and origin.endswith(".py"):
            files.append(Path(origin))
    return files


def _builtin_port_names() -> set[str]:
    from lynceus.nodes.ports import all_specs

    return {spec.display_name for spec in all_specs()}


def extract_core_strings() -> set[str]:
    """All core user-visible English strings (deterministic input set)."""
    out = set(_static_t_literals())
    for path in _core_node_files():
        out |= node_file_strings(path)
    out |= _builtin_port_names()
    out = {s for s in out if s and s.strip() and not _is_number(s)}
    return out


def core_strings_snapshot() -> dict:
    """Versioned snapshot payload for `locales/_core_strings.json`."""
    return {"version": SNAPSHOT_VERSION, "strings": sorted(extract_core_strings())}


def write_core_strings_snapshot(path: str | Path) -> Path:
    """Write the snapshot file (used by simulations + the snapshot tool)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(core_strings_snapshot(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return path


class ExtractTests(unittest.TestCase):
    def test_extraction_is_deterministic(self) -> None:
        self.assertEqual(extract_core_strings(), extract_core_strings())

    @unittest.skipUnless(
        IS_CORE_CHECKOUT, "needs a core checkout (lynceus/ sources)"
    )
    def test_extraction_is_substantial(self) -> None:
        strings = extract_core_strings()
        self.assertGreater(len(strings), 400)
        for probe in ("Generate DTM", "Point Cloud", "Segment {k}/{n}"):
            self.assertIn(probe, strings)

    def test_snapshot_roundtrip(self) -> None:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = write_core_strings_snapshot(Path(tmp) / "_core_strings.json")
            doc = json.loads(path.read_text(encoding="utf-8"))
            self.assertEqual(doc["version"], SNAPSHOT_VERSION)
            self.assertEqual(doc["strings"], sorted(extract_core_strings()))


if __name__ == "__main__":
    unittest.main()
