# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Locale-pack coverage: every enabled language covers every string.

Runs in two layouts (auto-detected):
- extensions repo: packs at `locales/<lang>/<lang>.json`, own nodes at
  `nodes/**`, core snapshot at `locales/_core_strings.json`;
- dev checkout: packs at `extensions/locales/...`, own nodes at
  `extensions/nodes/**` (same snapshot filename).

The snapshot is regenerated by the snapshot tool on each core release —
never hand-edited. Missing snapshot or packs → skip with a clear reason.
Review decisions about translations (ALLOW_*) live here, next to the packs
(the dev-wide guardian in `test_i18n_nodes.py` keeps its own copies).
"""

import json
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

LANGS = ("es", "ru", "it", "pt-BR", "zh", "hi", "ar", "fr", "bn")

ALLOW_IDENTICAL = {
    "LiDAR", "CHM", "DSM", "DTM", "CHM A", "CHM B", "LAZ", "LAS",
    "NODATA", "GeoPackage", "GeoTIFF", "CSV", "JSON", "LAI", "PMF",
    "CSF", "SMRF", "MCC", "ATIN", "NDVI", "NDRE", "GNDVI", "SAVI", "VARI", "GLI",
    "QGIS", "CRS", "EPSG", "WGS84", "ASPRS", "GPKG", "RGB", "EULA",
    "Color", "Copyright", "Inspector", "General", "Backend",
    "x {x}  y {y}", "{size} ({p}%)",
    "json", "csv", "sor", "ror", "SOR", "ROR",
    "first", "last", "single", "multiple",
    "Zoom 100%",
}

ALLOW_PER_LANG = {
    "it": {"File", "Input", "Output", "Raster", "Repository", "Copyright",
           "Area"},
    "pt-BR": {"Raster", "classes", "latitude", "longitude"},
    "fr": {
        # Genuine French cognates / established French UI conventions.
        "Pause", "Extensions", "Extensions...", "Description", "Copyright",
        "Documentation", "Raster", "Segmentation", "Terrain", "Version",
        "Classification", "Segment {k}/{n}",
        "Segment {k}/{n} · {points} points", "max {v}", "min {v}",
        "latitude", "longitude", "(minimum)", "Performance", "Contact",
        "Multispectral", "Image", "action", "classes", "mode",
        "exclusion",
    },
    "es": set(),
    "ru": set(),
    "zh": set(),
    "hi": set(),
    "ar": set(),
    "bn": set(),
}

ALLOW_SAME_SPELLING = {
    "es": {"General"},
    "ru": set(),
    "it": set(),
    "pt-BR": set(),
    "zh": set(),
    "hi": set(),
    "ar": set(),
    "fr": set(),
    "bn": set(),
}


def _packs_dir() -> Path | None:
    for candidate in (ROOT / "locales", ROOT / "extensions" / "locales"):
        if (candidate / "es" / "es.json").is_file():
            return candidate
    return None


def _own_nodes_dir() -> Path | None:
    for candidate in (ROOT / "nodes", ROOT / "extensions" / "nodes"):
        if candidate.is_dir():
            return candidate
    return None


def _load_catalog(packs: Path, lang: str) -> dict:
    return json.loads((packs / lang / f"{lang}.json").read_text(encoding="utf-8"))[lang]


def _is_number(text: str) -> bool:
    try:
        float(text)
        return True
    except ValueError:
        return False


class CoverageTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        packs = _packs_dir()
        if packs is None:
            raise unittest.SkipTest("no locale packs found")
        snapshot_path = packs / "_core_strings.json"
        if not snapshot_path.is_file():
            raise unittest.SkipTest(
                f"missing {snapshot_path.name}: regenerate it with the "
                "snapshot tool (never hand-edit)"
            )
        cls.packs = packs
        cls.catalogs = {lang: _load_catalog(packs, lang) for lang in LANGS}
        doc = json.loads(snapshot_path.read_text(encoding="utf-8"))
        cls.required = set(doc["strings"])
        assert doc.get("version") == 1, "unsupported snapshot version"
        assert len(cls.required) > 400, "snapshot looks truncated"

        from test_i18n_extract import node_file_strings

        own = set()
        nodes = _own_nodes_dir()
        if nodes is not None:
            for path in sorted(nodes.rglob("*.py")):
                if "__pycache__" in path.parts or "/cache/" in path.as_posix():
                    continue
                own |= node_file_strings(path)
        cls.required |= {s for s in own if s and s.strip()}

    def _assert_covered(self, lang: str, text: str, where: str) -> None:
        if not text or not text.strip() or _is_number(text):
            return
        if text in ALLOW_IDENTICAL:
            return
        cat = self.catalogs[lang]
        self.assertIn(text, cat, f"missing {lang} key for {where}: {text!r}")
        if text in ALLOW_PER_LANG.get(lang, set()):
            return
        if text in ALLOW_SAME_SPELLING.get(lang, set()):
            self.assertEqual(cat[text], text)
            return
        self.assertNotEqual(
            cat[text], text, f"{lang} fallback (untranslated) for {where}: {text!r}"
        )

    def test_packs_cover_all_strings(self) -> None:
        for lang in LANGS:
            for text in sorted(self.required):
                with self.subTest(lang=lang, key=text):
                    self._assert_covered(lang, text, "coverage")

    def test_catalog_parity(self) -> None:
        keys = [set(cat) for cat in self.catalogs.values()]
        for lang, keyset in zip(LANGS, keys):
            self.assertEqual(keys[0], keyset, f"es/{lang} key mismatch")

    def test_placeholders_survive_translation(self) -> None:
        for lang in LANGS:
            for key, value in self.catalogs[lang].items():
                if key in ALLOW_IDENTICAL or key in ALLOW_PER_LANG[lang]:
                    continue
                with self.subTest(lang=lang, key=key):
                    self.assertEqual(
                        sorted(set(re.findall(r"\{[^{}]*\}", key))),
                        sorted(set(re.findall(r"\{[^{}]*\}", value))),
                        f"placeholder mismatch for {key!r}",
                    )


if __name__ == "__main__":
    unittest.main()
